
version: '3'
services:
  web-app:
     container_name: covid-app-dev
     build:
      context: .
      dockerfile: Dockerfile
     ports:
      - 3002:${PORT}
    #  env_file:
    #   - .env.development
     volumes:
      - '.:/app'
      # - '/app/node_modules'
     environment:
      #  - CHOKIDAR_USEPOLLING=true
     - REACT_APP_ENVIRNOMENT=${REACT_APP_COMPOSE}
