version: '3'
services:
  web:
     container_name: covid-app-prod3
     build:
      context: .
      dockerfile: Dockerfile.prod
    #  env_file:
    #   - .env.production
     volumes:
      - '.:/app'
      - '/app/node_modules'
     ports:
      - "3005:8080"
     environment:
      #  - CHOKIDAR_USEPOLLING=true
     - REACT_APP_ENVIRNOMENT=${REACT_APP_COMPOSE}

     